# Generated by Django 3.2.14 on 2022-07-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField()),
                ('thumbnail_url_default', models.URLField(max_length=100)),
                ('thumbnail_url_medium', models.URLField(max_length=100)),
                ('thumbnail_url_high', models.URLField(max_length=100)),
            ],
        ),
    ]
