# Generated by Django 3.2.14 on 2023-06-05 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_ytdata_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ytdata',
            index=models.Index(fields=['published_at'], name='core_ytdata_publish_7562fc_idx'),
        ),
        migrations.AddIndex(
            model_name='ytdata',
            index=models.Index(fields=['title'], name='core_ytdata_title_1b338a_idx'),
        ),
    ]
